### ISSUE TITLE
package.json is incorrect

### ISSUE THREAD

**Issue by ericeslinger** [localForage-extensions/localForage-getItems#1]
Line https://github.com/localForage-extensions/localForage-getItems/blob/master/package.json#L35 indicates that the main file should be localforage-getItems.js, when it is in fact localforage-getitems.js

On case-sensitive filesystems (linux), this causes the import to fail.

**Comment by thgreasi** [comment]
Just pushed v1.2 that uses es6 modules and rollup. I think that this can be closed now. Please confirm that it works for you.
