### ISSUE TITLE
getting all the items

### ISSUE THREAD

**Issue by wclr** [localForage-extensions/localForage-getItems#3]
What do you think about API addition: getting all the items in store if `keys` is nil?

**Comment by thgreasi** [comment]
I would prefer to call the method without any argument so that we can be
safer that we don't accidentally retrieve the whole database. I will
investigate during the weekend whether using iterate() or Promise.all() +
getItems() + keys() is preferable.

> ## 
> 
> _Thodoris Greasidis_

**Comment by thgreasi** [comment]
Released with 4a150cc6fa37a8ae23b53da7facd5395478b1a15 as [v1.3.0](https://github.com/localForage-extensions/localForage-getItems/releases/tag/v1.3.0). Also added some documentation to README.
Thanks for the suggestions :+1:

**Comment by wclr** [comment]
Nice, thanks)
