### ISSUE TITLE
getItems mutates its argument

### ISSUE THREAD

**Issue by lambda-fairy** [localForage-extensions/localForage-getItems#9]
`getItems` sorts its input array in-place, which can lead to surprising behavior if the array is used later:

```javascript
var keys = ['b', 'c', 'a'];
await localforage.getItems(keys);
console.log(keys);  // ['a', 'b', 'c']
```

Changing [this line](https://github.com/localForage/localForage-getItems/blob/8543cd3bb4405c64d3d30627fc959f3004e98db8/lib/getitems-indexeddb.js#L16) to `keys.slice().sort(comparer)` should fix the bug, though I haven't tested it.

**Comment by thgreasi** [comment]
Thanks for opening this issue, TBH I never thought that this could affect anyone.
